### PR TITLE
Modify CMakeLists for build

### PR DESCRIPTION
**Pull request by tongtybj**
@shuto1441 

Please try this branch by following steps
```
$ git remote add chou git@github.com:tongtybj/test-1.git
$ git fetch chou
$ git checkout -b cmake_fix chou/cmake_fix
$ catkin bt
```

### CODE REVIEW

**Comment by shuto1441** [comment]
fetch cannot be done 

`$git fetch chou`

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by tongtybj** [comment]
soory, please chane to folliwing URL. Because you do not have permission of SSH, you have to use https based URL.

https://github.com/tongtybj/test-1.git

**Comment by shuto1441** [comment]
Thank you!
modbus_motor.cpp  following include path error cannot be fixed.
`#include <test/modbus_motorConfig.h>`

but dynamic_reconfigure can be used and the screen for setting parameters is launched.

**Comment by tongtybj** [comment]
I build with terminal directly (without VSCode), and succeeded to compile all stuff. So I wonder this is an issue related to VSCode. 
I am not familiar with VSCode path setting, but you might have to manually add the path of the cfg generated header file...
Please check whether there is header file `modbus_motorConfig.h` of under `~/ros/catkin_ws/devel/include/test`

**Comment by shuto1441** [comment]
I'm sorry, I was mistaken.

include path can be corrected, and error can be fixed

**Pull request merged**
